# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b13833602395c6d4a8383ac4537c116bddc55992063d241d501884dedf51c7b41e9bfa364842ece7f907a3723492179f37325801c27770c9b5dab121607a31e

test:
  secret_key_base: 7f21c0eb6677d6438fdae521914433a2491d8897609abb36e576e5b05426427add7878d8289ef8cf9a4e9b5ecc1227f0616f6d8aff69723122b4c6c2fcd62c22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
